name: Jalankan Robot Pengambil Angka

on:
  push:
    branches: [ main ]
  schedule:
    # Perintah di bawah ini artinya: Robot akan berjalan otomatis setiap 1 jam sekali.
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Memberikan izin kepada robot untuk mengedit & menyimpan angka baru ke pools.json

    steps:
    - name: Mengambil kode dari repositori
      uses: actions/checkout@v4

    - name: Menyiapkan Lingkungan Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Menjalankan Skrip Scraper
      run: node scraper.js

    - name: Menyimpan Perubahan Kembali Ke GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add pools.json
        git commit -m "Otomatis: Perbaruan data nomor pasaran" || exit 0
        git push
